# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

{{- if and .Values.kubernetes.gatewayAPI.enabled .Values.kubernetes.gatewayAPI.controlPlane.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "apim-helm-cp.fullname" . }}-httproute
  namespace: {{ .Release.Namespace }}
{{- if .Values.kubernetes.gatewayAPI.controlPlane.annotations }}
  annotations:
{{ toYaml .Values.kubernetes.gatewayAPI.controlPlane.annotations | indent 4 }}
{{- end }}
spec:
  parentRefs:
  - name: {{ template "apim-helm-cp.fullname" . }}-gateway
    sectionName: controlplane-https
  hostnames:
  - {{ .Values.kubernetes.gatewayAPI.controlPlane.hostname }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ template "apim-helm-cp.fullname" . }}-service
      port: 9443
    {{- if .Values.kubernetes.gatewayAPI.controlPlane.filters }}
    filters:
{{ toYaml .Values.kubernetes.gatewayAPI.controlPlane.filters | indent 4 }}
    {{- end }}
{{- end }}
